### 1. 정상 요청 예시
GET http://localhost:3000/api/search/Electronics

### 유효하지 않은 입력 (숫자 포함)
GET http://localhost:3000/api/search/1234

### 공백 포함 카테고리 예시
GET http://localhost:3000/api/search/Home%20Appliances

### 2
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "userId": "abc123"
}

###3
GET http://localhost:3000/api/posts/search?keyword=example
Accept: application/json

###4
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "alice",
  "password": "mypassword123"
}

###5
DELETE http://localhost:3000/api/todo/delete
Content-Type: application/json

{
  "_id": 2
}